import { defineSlotRecipe } from "@chakra-ui/react";

export const busMapPopupRecipe = defineSlotRecipe({
  className: "bus-map-popup",
  slots: [
    "popupContainer",
    "approachingBox",
    "approachingHeader",
    "approachingRow",
    "approachingBusName",
    "approachingDestination",
    "noBusBox",
    "noBusText",
    "sectionHeader",
    "timelineContainer",
    "timelineItem",
    "timelineDotPrev",
    "timelineDotActive",
    "timelineDotNextNext",
    "timelineText",
    "timelineTime",
    "statusFlex",
    "statusLabel",
  ],
  base: {
    popupContainer: {
      minW: "260px",
    },
    approachingBox: {
      bg: "orange.50",
      p: "2",
      borderRadius: "md",
      my: "2",
      border: "1px solid",
      borderColor: "orange.200",
    },
    approachingHeader: {
      fontSize: "xs",
      color: "orange.700",
      mb: "1",
    },
    approachingRow: {
      py: "1",
      _notFirst: {
        borderTop: "1px dashed",
        borderColor: "orange.200",
        mt: "1",
      },
    },
    approachingBusName: {
      fontSize: "xs",
      color: "gray.700",
      fontWeight: "bold",
    },
    approachingDestination: {
      fontSize: "10px",
      color: "blue.600",
      mt: "0.5",
      fontWeight: "medium",
    },
    noBusBox: {
      bg: "gray.50",
      p: "1.5",
      borderRadius: "md",
      my: "2",
      textAlign: "center",
    },
    noBusText: {
      fontSize: "xs",
      color: "gray.500",
    },
    sectionHeader: {
      fontSize: "xs",
      color: "fg.muted",
      mb: "2",
    },
    timelineContainer: {
      pl: "2",
      borderLeft: "2px solid",
      borderColor: "blue.100",
      position: "relative",
    },
    timelineItem: {
      position: "relative",
      mb: "3",
      _last: { mb: 0 },
    },
    timelineDotPrev: {
      position: "absolute",
      left: "-13px",
      top: "4px",
      w: "8px",
      h: "8px",
      borderRadius: "full",
      bg: "gray.300",
    },
    timelineDotActive: {
      position: "absolute",
      left: "-13px",
      top: "3px",
      w: "10px",
      h: "10px",
      borderRadius: "full",
      bg: "green.500",
    },
    timelineDotNextNext: {
      position: "absolute",
      left: "-13px",
      top: "4px",
      w: "8px",
      h: "8px",
      borderRadius: "full",
      bg: "orange.400",
    },
    timelineText: {
      fontSize: "xs",
      display: "flex",
      alignItems: "center",
      w: "full",
    },
    timelineTime: {
      color: "blue.600",
      ms: "auto",
      textAlign: "right",
    },
    statusFlex: {
      alignItems: "center",
      gap: "1",
    },
    statusLabel: {
      fontSize: "xs",
      fontWeight: "bold",
    },
  },
});